#cloud-config
#
#Set Hostname
hostname: CoreBM1

coreos:
  etcd:
  # Genero un nuevo Token para el cluster desde  https://discovery.etcd.io/new
  discovery: https://discovery.etcd.io/d8fbabc3377c4ec513faa697c69da481

  units:
    - name: etcd.service
      command: start
    - name: fleet.service
      command: start
    - name: static.network
      content: |
        [Match]
        Name=en*
        [Network]
        Address=192.168.1.10/24
        Gateway=192.168.1.1
        DNS=200.48.225.130
        DNS=200.48.225.146

users:
  - name: core
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDYTC/VWeVnhzwVh+RPBlffEJMWbD+Otl2IHwpCjHSVRHx8i8SSqvHj5vJo9ElFMTScLkJ/6LJtw+XMwFYUli3oAsxSIQi6a4oHVT1NfM3z9q6xfkO6QJjs1I8LuX3dd8szfv8ZSZbnGUhTPYSugJvpITlPEpoM+LvCZqezK2TGDfPpXqmLFpYGcnetAVU9EJRcUU7tpDpq0Keo6cOMOvT0NvQtDrHAJiabavWpUwrk17+eOAzIaur64YrmwymIMophQ/oVq4iBWqREJNWi701L+GyOtRUAo5yC30oQ/oChG5lmtB8axzzYrPY/8ZOykVsRO6sdxDjH2Komyv4zYiXX necugar@ncgmac.local
  - groups:
      - sudo
      - docker
